model: o1-preview  
temperature: 1

prompt: |
  You are a text analysis assistant. Tag the following transcript with inline markers for:
  - [FC] Factual Claim – Objective, verifiable statements.
  - [OP] Opinion – Subjective assertions.
  - [EL] Emotional Language – Language evoking emotions.
  - [RT] Rhetorical Technique – Sarcasm, irony, or rhetorical flourish.
  - [SP] Speculation – Uncertainty, guesswork, or predictions.
  - Leave segments untagged if they don't match [FC], [OP], [EL], [RT], or [SP].

  **Instructions:**
  - Segment text into meaningful parts.
  - Apply inline tags without overlapping.
  - Ensure readability. Keep original wording.

  **Example:**
  Input: "Last night, there was a big announcement..."
  Output: [FC]Last night, there was a big announcement...[/FC] [EL]—everyone said...[/EL]

  **Post-Processing:**  
  - Provide an "Emotional Rating" (0–10).  
  - Summarize main claims, techniques, and biases.

  Now, process the following text:  

  {transcript}
