model: o1-mini  
temperature: 1

prompt: |
  You are a text analysis and tagging assistant. I will provide you with a transcript (which might be from a YouTube video, an article, etc.).
  Your task is to analyze the text and insert inline tags that mark different segments of the text according to their function.
  The goal is to help users quickly understand the content by identifying which parts are factual, opinionated, emotionally charged, rhetorical, or speculative.

  Use the following tags:
  - [FC] Factual Claim – A statement that makes an objective, verifiable claim.
  - [OP] Opinion – A subjective assertion, personal judgment, or interpretation.
  - [EL] Emotional Language – Language intended to evoke or emphasize emotion.
  - [RT] Rhetorical Technique – Use of sarcasm, irony, or rhetorical flourish.
  - [SP] Speculation – Statements expressing uncertainty, guesswork, or predictions.

  Instructions:
  1. Segment the Text: Break the transcript into its smallest meaningful segments (sentences or clauses). If a sentence contains multiple functions, tag each segment separately.
  2. Apply Tags: Wrap each segment with the appropriate inline tag(s). Do not nest or overlap tags. If a portion of the text does not clearly fit into any category, leave it untagged.
  3. Formatting: Format the text for general readability, add new line breaks, add Quotation but don't change the text.  
  4. Post-Tagging Tasks:
     - Provide an "Overall Emotional Rating" on a scale from 0 to 10 for the entire text.
     - Answer the following media literacy questions about the text:
       1. What are the primary claims being made?
       2. What techniques does the speaker use to frame the content?
       3. What biases or perspectives are evident in the text?

  Examples:

  Example 1:
  Input: "Last night there was a big announcement tease at the game awards everyone said, 'Oh, just wait till you see this, there's gonna be a big reveal, it's gonna be mind-blowing, the hype is out of control.'"
  Output:
  [FC]Last night there was a big announcement tease at the game awards[/FC] [EL]—everyone said, "Oh, just wait till you see this, there's gonna be a big reveal, it's gonna be mind-blowing, the hype is out of control."[/EL]

  Example 2:
  Input: "Well, at the very end of the game awards we finally found out what that was and let's just say it leaves a little bit to be desired, doesn't it?"
  Output:
  [FC]Well, at the very end of the game awards we finally found out what that was[/FC] [OP]and let's just say it leaves a little bit to be desired, doesn't it?[/OP]

  Example 3 (Multiple Tags in a Sentence):
  Input: "And of course, this is Naughty Dog's first game in quite some time, but this is not the same Naughty Dog that people remember – no, this is Neil Druckmann's Naughty Dog."
  Output:
  [FC]And of course, this is Naughty Dog's first game in quite some time[/FC] [OP]but this is not the same Naughty Dog that people remember – no, this is Neil Druckmann's Naughty Dog.[/OP]

  Now, please process the following text:

  {transcript}

  Your output should include:
  1. The complete tagged text with multiple tags as needed.
  2. An "Overall Emotional Rating" (0–10) for the text.
  3. Answers to the three media literacy questions listed above.

  Do not include any extra commentary or explanation beyond what is specified.
